version: '3.3'

services:
  app:
    container_name: "${DOCKER_PROJECT_NAME_UNDERSCORE}_app"
    build:
      context: ./docker
      dockerfile: Dockerfile-app
    ports:
      - "100:80"
      - "200:443"
    restart: always
    depends_on:
      - db
    volumes:
      - ".:/var/www/${DOCKER_PROJECT_NAME_DASH}"

  db:
    container_name: "${DOCKER_PROJECT_NAME_UNDERSCORE}_db"
    build:
      context: ./docker
      dockerfile: Dockerfile-db
    ports:
      - "300:3306"
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: $DB_PASSWORD
       MYSQL_DATABASE: $DB_DATABASE
       MYSQL_USER: $DB_USERNAME
       MYSQL_PASSWORD: $DB_PASSWORD
